### ISSUE TITLE
ERROR: [Common 17-69] Command failed: Run 'impl_1' has not been launched. Unable to open

### ISSUE THREAD

**Issue by ohmmaxmaBOY** [Avnet/vitis#1]
Hello, I try to make ultra96v2_oob on 2020.1 branch but it's error on implement step after impl process finish.I'm try to fix bug from error 

>  ***** Wait for bitstream to be written...
[Thu Oct 22 21:10:29 2020] Waiting for impl_1 to finish...
[Thu Oct 22 21:20:13 2020] impl_1 finished
WARNING: [Vivado 12-8222] Failed run(s) : 'ULTRA96V2_zynq_ultra_ps_e_0_0_synth_1', 'ULTRA96V2_clk_wiz_0_0_synth_1', 'ULTRA96V2_blk_mem_gen_0_0_synth_1'
wait_on_run: Time (s): cpu = 00:00:04 ; elapsed = 00:09:44 . Memory (MB): peak = 3915.863 ; gain = 0.000 ; free physical = 2688 ; free virtual = 3633
***** Open the implemented design...
ERROR: [Common 17-69] Command failed: Run 'impl_1' has not been launched. Unable to open
    while executing
"source ./ProjectScripts/$project.tcl -notrace"
    ("ULTRA96V2" arm line 2)
    invoked from within
"switch -nocase $board {
   PZ7015_FMCCC               -
   PZ7030_FMCCC               -
   PZ7010_FMC2                -
   PZ7020_FMC2                ..."
    (file "./make.tcl" line 361)
    while executing
"source ./make.tcl -notrace"
    (file "make_ultra96v2_oob.tcl" line 59)
INFO: [Common 17-206] Exiting Vivado at Thu Oct 22 21:20:14 2020...
vitis_ULTRA96V2_Makefile:2: recipe for target 'xsa' failed
make[2]: *** [xsa] Error 1
make[2]: Leaving directory '/home/ohm/titanproject/Vitis_AI_Project/resource/software/hdl/Scripts'
../projectMakefile.mk:106: recipe for target 'xsa' failed
make[1]: *** [xsa] Error 2
make[1]: Leaving directory '/home/ohm/titanproject/Vitis_AI_Project/resource/software/vitis/ultra96v2_oob'
Makefile:110: recipe for target 'ultra96v2_oob' failed
make: *** [ultra96v2_oob] Error 2

First off all, i check hdl/Script/make_ultra96v2_oob.tcl it's call make.tcl on same path,
then i check make.tcl on line 361 has ULTRA96V2 call the board in hdl project has that board,
lastest i check hdl/Scripts/ProjectScrits/ultra96_oob.tcl only open impl. 
So can you advise me about this problem or only Vitis 1.1 can work now

**Comment by zedman2000** [comment]
Hi, we have not completed our work on this branch at this time, that could still be errors - especially as we just checked in code last night.  If you update all 4 repositories with what is there today, you likely will see all code related errors go away as we are today staging for tagging.
Secondly, make sure that you have followed the Avnet VM install guide, as that provides a critical amount of setup to ensure that vivado and vitis can properly access all of their own libraries - note we have not issued the 2020.1 version at this time, as we were still making changes as we discovered new things to understand about the 2020.1 tools
Thirdly, make sure that you have all four repositories at the same level:
~/projects/mybuildproj/bdf
~/projects/mybuildproj/hdl
~/projects/mybuildproj/petalinux
~/projects/mybuildproj/vitis

**Comment by zedman2000** [comment]
Also, you should post for support on the Element14 support forums:
https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums
